# backend/core/digest/html_parser.py

# ============================================================
# GENERIC BLOCK PARSER
# ============================================================

def parse_blocks(
    text: str,
    block_name: str,
    body_name: str,
) -> list[dict[str, str]]:
    """
    Parse structured blocks generated by the LLM.
    """

    if not text:
        return []

    blocks = []

    parts = text.split(block_name)

    for part in parts:

        part = part.strip()

        if not part:
            continue

        if body_name not in part:
            continue

        title_part, body_part = part.split(
            body_name,
            maxsplit=1,
        )

        title = (
            title_part
            .replace("TITLE", "")
            .strip()
        )

        body = body_part.strip()

        blocks.append(
            {
                "title": title,
                "body": body,
            }
        )

    return blocks

# ============================================================
# MARKET DEVELOPMENTS
# ============================================================

def parse_market_developments(
    text: str,
) -> list[dict[str, str]]:
    """
    Parse the Key Points capability.
    """

    return parse_blocks(

        text=text,

        block_name="MARKET DEVELOPMENT",

        body_name="SUMMARY",

    )


# ============================================================
# STRATEGIC IMPLICATIONS
# ============================================================

def parse_implications(
    text: str,
) -> list[dict[str, str]]:
    """
    Parse the Strategic Implications capability.
    """

    return parse_blocks(

        text=text,

        block_name="STRATEGIC IMPLICATION",

        body_name="ANALYSIS",

    )
