from datetime import (
    datetime,
)

from typing import (
    Any,
    Literal,
)

from pydantic import (
    BaseModel,
    Field,
)


# ============================================================
# TYPES
# ============================================================

TouchEvidenceNoteType = Literal[
    "FACT",
    "MECHANISM",
    "NUMBER",
    "STRATEGIC_READING",
    "TENSION",
    "LIMITATION",
    "UNCERTAINTY",
    "COMPARISON",
    "MILESTONE",
    "EXAMPLE",
]


TouchEvidenceConfidence = Literal[
    "HIGH",
    "MEDIUM",
    "LOW",
]


TouchEvidenceStatus = Literal[
    "VALIDATED",
    "TO_VERIFY",
    "CONTRADICTED",
]


TouchGenerationStatus = Literal[
    "GENERATED",
    "GENERATION_FAILED",
]

TouchReportArchetype = Literal[
    "DOCUMENTARY_SYNTHESIS",
    "COMPARATIVE_ANALYSIS",
    "CROSS_CONTEXT_ANALYSIS",
]


TouchReportOrganization = Literal[
    "THEMATIC",
    "CHRONOLOGICAL",
    "HYBRID",
]


TouchReportTimeGranularity = Literal[
    "AUTO",
    "MONTH",
    "QUARTER",
    "YEAR",
]


TouchNotebookResearchType = Literal[
    "ENTITY",
    "COMPARATIVE",
    "CROSS_SECTOR",
    "TOPIC",
    "EVOLUTION",
    "EVENT",
    "MARKET",
    "OTHER",
]


TouchNotebookAxisType = Literal[
    "CORE_SUBJECT",
    "COMPARISON",
    "CONTEXT",
    "MECHANISM",
    "EVIDENCE",
    "LIMITATIONS",
    "EVOLUTION",
    "OTHER",
]


# ============================================================
# STRICT MODEL
# ============================================================

class StrictTouchNotebookModel(
    BaseModel,
):

    class Config:

        extra = "forbid"


# ============================================================
# NOTE
# ============================================================

class TouchEvidenceNote(
    StrictTouchNotebookModel,
):

    note_id: str

    input_note_ids: list[str] = Field(
        default_factory=list,
    )

    note_type: TouchEvidenceNoteType

    statement: str

    explanation: str = ""

    actors: list[str] = Field(
        default_factory=list,
    )

    geographies: list[str] = Field(
        default_factory=list,
    )

    dates: list[str] = Field(
        default_factory=list,
    )

    confidence: TouchEvidenceConfidence

    status: TouchEvidenceStatus = (
        "VALIDATED"
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )


# ============================================================
# CERTIFIED NUMBER ENTITY
# ============================================================

class TouchNotebookNumberEntity(
    StrictTouchNotebookModel,
):

    entity_type: str | None = None

    entity_id: str | None = None

    entity_label: str | None = None


# ============================================================
# CERTIFIED NUMBER
# ============================================================

class TouchNotebookNumber(
    StrictTouchNotebookModel,
):
    """
    Touch representation of one effectively ACCEPTED
    Number observation.

    The values are copied from the canonical Numbers
    service and are not generated by the Touch LLM.
    """

    number_id: str

    id_content: str

    label: str | None = None

    metric_type: str | None = None

    value: Any = None

    value_min: Any = None

    value_max: Any = None

    unit: str | None = None

    scale: str | None = None

    zone: str | None = None

    period_label: str | None = None

    value_status: str | None = None

    confidence: float = 0

    entities: list[
        TouchNotebookNumberEntity
    ] = Field(
        default_factory=list,
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )


# ============================================================
# EVENT
# ============================================================

class TouchNotebookEvent(
    StrictTouchNotebookModel,
):

    event_id: str

    title: str

    description: str

    event_date: str | None = None

    actors: list[str] = Field(
        default_factory=list,
    )

    note_ids: list[str] = Field(
        default_factory=list,
    )

    number_ids: list[str] = Field(
        default_factory=list,
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )


# ============================================================
# TIMELINE ITEM
# ============================================================

class TouchNotebookTimelineItem(
    StrictTouchNotebookModel,
):

    date: str

    label: str

    description: str = ""

    event_id: str | None = None

    note_ids: list[str] = Field(
        default_factory=list,
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )


# ============================================================
# QUARANTINED NUMBER
# ============================================================

class TouchQuarantinedNumber(
    StrictTouchNotebookModel,
):
    """
    Retained temporarily for API compatibility.

    Certified Touch Numbers do not enter this collection.
    Rejected or review-required observations remain inside
    the Numbers workflow.
    """

    value: str

    unit: str = ""

    metric: str = ""

    context: str = ""

    reason: str

    source_content_ids: list[str] = Field(
        default_factory=list,
    )


# ============================================================
# CONTRADICTION
# ============================================================

class TouchNotebookContradiction(
    StrictTouchNotebookModel,
):

    subject: str

    description: str

    note_ids: list[str] = Field(
        default_factory=list,
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )

    resolution: str | None = None


# ============================================================
# COVERAGE DIMENSION
# ============================================================

class TouchNotebookDimension(
    StrictTouchNotebookModel,
):

    label: str

    summary: str

    note_ids: list[str] = Field(
        default_factory=list,
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )

# ============================================================
# NOTEBOOK SECTION
# ============================================================

class TouchNotebookSection(
    StrictTouchNotebookModel,
):
    """
    One ordered documentary section.

    event_ids identify the events displayed in the section.

    note_ids contain only standalone notes that are not
    already attached to one of the section events.

    number_ids contain only standalone certified Numbers
    that are not already attached to one of the section
    events.
    """

    section_id: str

    title: str

    description: str = ""

    event_ids: list[str] = Field(
        default_factory=list,
    )

    note_ids: list[str] = Field(
        default_factory=list,
    )

    number_ids: list[str] = Field(
        default_factory=list,
    )

# ============================================================
# EXECUTIVE SUMMARY ITEM
# ============================================================

class TouchNotebookExecutiveSummaryItem(
    StrictTouchNotebookModel,
):

    summary_id: str

    statement: str

    note_ids: list[str] = Field(
        ...,
        min_length=1,
    )

    source_content_ids: list[str] = Field(
        default_factory=list,
    )

# ============================================================
# CORPUS NOTEBOOK
# ============================================================
class TouchCorpusNotebook(
    StrictTouchNotebookModel,
):

    subject: str

    objective: str

    corpus_summary: str

    executive_summary: list[
        TouchNotebookExecutiveSummaryItem
    ] = Field(
        default_factory=list,
    )

    sections: list[
        TouchNotebookSection
    ] = Field(
        default_factory=list,
    )

    notes: list[
        TouchEvidenceNote
    ] = Field(
        default_factory=list,
    )

    events: list[
        TouchNotebookEvent
    ] = Field(
        default_factory=list,
    )

    timeline: list[
        TouchNotebookTimelineItem
    ] = Field(
        default_factory=list,
    )

    dimensions: list[
        TouchNotebookDimension
    ] = Field(
        default_factory=list,
    )

    validated_numbers: list[
        TouchNotebookNumber
    ] = Field(
        default_factory=list,
    )

    quarantined_numbers: list[
        TouchQuarantinedNumber
    ] = Field(
        default_factory=list,
    )

    contradictions: list[
        TouchNotebookContradiction
    ] = Field(
        default_factory=list,
    )

    corpus_strengths: list[str] = Field(
        default_factory=list,
    )

    corpus_limits: list[str] = Field(
        default_factory=list,
    )

# ============================================================
# NOTEBOOK CONTRIBUTION
# ============================================================

class TouchNotebookContribution(
    StrictTouchNotebookModel,
):

    content_id: str

    statements: list[str] = Field(
        ...,
        min_length=1,
    )

# ============================================================
# NOTEBOOK RESEARCH AXIS
# ============================================================

class TouchNotebookResearchAxis(
    StrictTouchNotebookModel,
):

    axis_id: str

    axis_type: TouchNotebookAxisType

    label: str

    objective: str

    search_terms: list[str] = Field(
        default_factory=list,
    )

    related_angles: list[str] = Field(
        default_factory=list,
    )


# ============================================================
# NOTEBOOK REPORT DESIGN
# ============================================================

class TouchNotebookReportDesign(
    StrictTouchNotebookModel,
):

    report_archetype: TouchReportArchetype = (
        "DOCUMENTARY_SYNTHESIS"
    )

    organization_mode: TouchReportOrganization = (
        "THEMATIC"
    )

    time_granularity: TouchReportTimeGranularity = (
        "AUTO"
    )

    research_type: (
        TouchNotebookResearchType
        | None
    ) = None

    central_question: str = ""

    scope_summary: str = ""

    target_context: str | None = None

    period_start: datetime | None = None

    period_end: datetime | None = None

    geographies: list[str] = Field(
        default_factory=list,
    )

    axes: list[
        TouchNotebookResearchAxis
    ] = Field(
        default_factory=list,
    )

    assumptions: list[str] = Field(
        default_factory=list,
    )

    editorial_cautions: list[str] = Field(
        default_factory=list,
    )

    missing_information: list[str] = Field(
        default_factory=list,
    )

# ============================================================
# REQUEST
# ============================================================

class TouchNotebookRequest(
    StrictTouchNotebookModel,
):

    report_id: str | None = None

    subject: str

    objective: str = ""

    content_ids: list[str] = Field(
        ...,
        min_length=1,
    )

    contributions: list[
        TouchNotebookContribution
    ] = Field(
        ...,
        min_length=1,
    )

    output_language: str = "fr"

    report_design:
        TouchNotebookReportDesign = Field(
            default_factory=(
                TouchNotebookReportDesign
            ),
        )

# ============================================================
# OUTCOME
# ============================================================

class TouchNotebookOutcome(
    StrictTouchNotebookModel,
):

    status: TouchGenerationStatus

    notebook: TouchCorpusNotebook | None = None
    report_id: str | None = None
    source_count: int = 0

    error: str | None = None


